
.mgx
public
assets
coach-ayse-yilmaz.jpg
coach-ayse-yilmaz_variant_1.jpg
coach-ayse-yilmaz_variant_10.jpg
coach-ayse-yilmaz_variant_11.jpg
coach-ayse-yilmaz_variant_12.jpg
coach-ayse-yilmaz_variant_2.jpg
coach-ayse-yilmaz_variant_3.jpg
coach-ayse-yilmaz_variant_4.jpg
coach-ayse-yilmaz_variant_5.jpg
coach-ayse-yilmaz_variant_6.jpg
coach-ayse-yilmaz_variant_7.jpg
coach-ayse-yilmaz_variant_8.jpg
coach-ayse-yilmaz_variant_9.jpg
coach-mehmet-kaya.jpg
coach-mehmet-kaya_variant_1.jpg
coach-mehmet-kaya_variant_10.jpg
coach-mehmet-kaya_variant_11.jpg
coach-mehmet-kaya_variant_12.jpg
coach-mehmet-kaya_variant_2.jpg
coach-mehmet-kaya_variant_3.jpg
coach-mehmet-kaya_variant_4.jpg
coach-mehmet-kaya_variant_5.jpg
coach-mehmet-kaya_variant_6.jpg
coach-mehmet-kaya_variant_7.jpg
coach-mehmet-kaya_variant_8.jpg
coach-mehmet-kaya_variant_9.jpg
coach-zeynep-demir.jpg
coach-zeynep-demir_variant_1.jpg
coach-zeynep-demir_variant_10.jpg
coach-zeynep-demir_variant_11.jpg
coach-zeynep-demir_variant_12.jpg
coach-zeynep-demir_variant_2.jpg
coach-zeynep-demir_variant_3.jpg
coach-zeynep-demir_variant_4.jpg
coach-zeynep-demir_variant_5.jpg
coach-zeynep-demir_variant_6.jpg
coach-zeynep-demir_variant_7.jpg
coach-zeynep-demir_variant_8.jpg
coach-zeynep-demir_variant_9.jpg
images
Coaching.jpg
ICFPCCCertification.jpg
logos
favicon.ico
payment-callback.html
public:favicon-40x40.png
robots.txt
sitemap.xml
ss
src
components
admin
AdminNavbar.tsx
charts
BarChart.tsx
DoughnutChart.tsx
LineChart.tsx
PieChart.tsx
coach
CoachCard.tsx
CoachList.tsx
ui
AIEnhancedPostCard.tsx
CalendarIntegrationButtons.tsx
CoachBadges.tsx
CookieConsent.tsx
EventForm.tsx
EventView.tsx
Footer.tsx
ImageUpload.tsx
InvoiceGenerator.tsx
JobDetail.tsx
JobForm.tsx
MeetingRoom.tsx
Navbar.tsx
NotificationBell.tsx
PollModal.tsx
PollView.tsx
PostCard.tsx
PostComposer.tsx
PremiumBoostModal.tsx
PremiumPromotionToast.tsx
ReactionBar.tsx
SessionRefresher.tsx
SuccessSection.tsx
VerificationBadgeModal.tsx
config
adminFeatures.ts
contexts
AuthContext.tsx
FollowContext.tsx
LanguageContext.tsx
NotificationContext.tsx
SubscriptionContext.tsx
data
circleData.ts
heroSlides.ts
mentorCircleData.ts
mockData.ts
hooks
use-mobile.tsx
use-toast.ts
layouts
AdminLayout.tsx
PublicLayout.tsx
UserLayout.tsx
lib
aiAnalytics.ts
boostPayment.ts
calendarIntegration.ts
emailService.ts
excelExport.ts
i18n.ts
iyzico-simple.ts
iyzico.ts
jitsiMeet.ts
matchingService.ts
meeting-api.ts
paytr.ts
profileCompletion.ts
storage.ts
supabase.ts
uploadAvatar.ts
utils.ts
pages
About.tsx
AdminDashboard.tsx
AdminHireDashboard.tsx
AdminPanel.tsx
AdminProfile.tsx
AdminSettings.tsx
AdvancedAnalytics.tsx
Analytics.tsx
BireyselPremium.tsx
BookSession.tsx
BookingSystem.tsx
Boost.tsx
CerezPolitikasi.tsx
Checkout.tsx
CoachApplication.tsx
CoachDashboard.tsx
CoachProfile.tsx
CoachPublicProfile.tsx
CoachRequests.tsx
CoachSelection.tsx
CoachSelectionProcess.tsx
CoachSessions.tsx
CoachSettings.tsx
Coaches.tsx
Contact.tsx
CorporateDashboard.tsx
CorporateJobs.tsx
CorporateProfile.tsx
CorporateSettings.tsx
CreateJob.tsx
DanisanSozlesmesi.tsx
Dashboard.tsx
DebugAuth.tsx
DistanceSales.tsx
Ethics.tsx
Feed.tsx
ForCoaches.tsx
ForCompanies.tsx
ForgotPassword.tsx
Home.tsx
Howitworks.tsx
Index.tsx
Interview.tsx
InvestorDashboard.tsx
JobBoard.tsx
KVKKAydinlatma.tsx
KocSozlesmesi.tsx
KullanimSozlesmesi.tsx
Login.tsx
MeetingRoom.tsx
MentorCircle.tsx
MyApplications.tsx
MyAssessments.tsx
MyBookings.tsx
MyCalendar.tsx
MyInterviews.tsx
MyReports.tsx
MySessions.tsx
MySessionsHub.tsx
NotFound.tsx
NotificationCenter.tsx
Partnership.tsx
Payment.tsx
PaymentCallback.tsx
PaymentFailed.tsx
PaymentPage.tsx
PaymentSuccess.tsx
PaymentTest.tsx
PaytrCheckout.tsx
PersonalityTest.tsx
Pricing.tsx
PricingSimple.tsx
PricingTest.tsx
Privacy.tsx
Profile.tsx
Register.tsx
ResetPassword.tsx
Returns.tsx
RevenueModel.tsx
ReviewSystem.tsx
SavedItems.tsx
SessionJoin.tsx
SessionRoom.tsx
Sitemap.tsx
SubscriptionHistory.tsx
Terms.tsx
UserDashboard.tsx
UserProfile.tsx
UserProfileEdit.tsx
UserSessions.tsx
UserSettings.tsx
VideoSession.tsx
Webinar.tsx
Webinars.tsx
App.css
App.tsx
index.css
main.tsx
vite-env.d.ts
supabase
.env
.env.example
.gitignore
.vercelignore
Coaches
README.md
README_VERCEL.md
SUPABASE_SETUP.md
VERCEL_DEPLOYMENT_GUIDE.md
check_auth_context.js
check_database.sql
check_subs_direct.js
check_subscriptions.js
check_user_subscriptions.sql
components.json
debug_badge_issue.md
eslint.config.js
index.html
insert_test_badge.sql
insert_test_badge_fixed.sql
package.json
pnpm-lock.yaml
postcss.config.js
supabase-clean.sql
supabase-setup.sql
tailwind.config.ts
template_config.json
todo.md
tsconfig.app.json
tsconfig.json
tsconfig.node.json
vite.config.ts
